
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [6]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.shape(arr))
print(np.ndim(arr))
print(np.size(arr))
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[[0,2,-1]])

[1 3 8]



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:5])

[3 4 5]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print([[2,5,6]])

[[2, 5, 6]]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [16]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[arr>15])

[20 30 40 50 60]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [18]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr+10)

[20 30 40 50 60 70]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [20]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))

210
35.0
10
60



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [21]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.sort(arr))

[10 20 30 40 50 60]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [23]:
import numpy as np
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([11,22,33,44,55,66])
print(np.concatenate((arr1,arr2)))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[10 20 30 40 50 60 11 22 33 44 55 66]
[[10 20 30 40 50 60]
 [11 22 33 44 55 66]]
[10 20 30 40 50 60 11 22 33 44 55 66]
